### ISSUE TITLE
Avoid passing to plumed non-used arrays

### ISSUE THREAD

**Issue by PabloPiaggi** [PabloPiaggi/plumed2#3]
- Avoid to pass charges, masses, forces, and virial. This can give a 5-10x speedup as arrays have to be generated in python and this is slow.

**Comment by giovannipizzi** [comment]
I saw in the old implementation something like

```
_libplumed.plumed_cmd(self.main, 'setNoVirial', None)
```

maybe there is something similar (or something similar can be done) also for the other arrays?
