### ISSUE TITLE
Wrapper classes

### ISSUE THREAD

**Issue by PabloPiaggi** [PabloPiaggi/plumed2#4]
- Write wrapper classes to do specific tasks in an easier way, avoiding many explicit calls to the cmd interface. For example plumed.setPositions(pos) = plumed.cmd("setPositions",pos) .

**Comment by giovannipizzi** [comment]
I would suggest to have a different class, or a subclass, that exposes these methods, leaving the user with the 'base' class with access to all raw functionality.
