### ISSUE TITLE
Wrap python code in a python package

### ISSUE THREAD

**Issue by giovannipizzi** [PabloPiaggi/plumed2#7]
To avoid name clashes, maybe create a subfolder `python/plumed`, move the two .py files in this subfolder, and add `python/plumed/__init__.py`. Finally, in test/link/mainp.py, replace the import to

```
from plumed import plumed
from plumed import tools
```

or to keep the same way it is done now:

```
from plumed.plumed import *
from plumed.tools import *
```

**Comment by giovannipizzi** [comment]
Even better, one can move plumed.py to plumed/**init**.py, so one still needs to do only 

```
import plumed
```

but still 

```
import plumed.tools
```

If you agree, I can make quickly this change.

**Comment by PabloPiaggi** [comment]
Perfect. I agree it is better just doing "import plumed".

**Comment by giovannipizzi** [comment]
Done in 2af2b422e.
