### ISSUE TITLE
Still some files need to be written

### ISSUE THREAD

**Issue by giovannipizzi** [PabloPiaggi/plumed2#8]
If I don't call at least one of these two lines:

```
    plumed.cmd("action","PRINT ARG=q6.* FILE=colv")
    plumed.cmd("action","DUMPMULTICOLVAR DATA=q6 FILE=MULTICOLVAR.xyz")
```

the grabbed data contains only NaN.
However, both write on files.
Is it expected that at least one of the two calls is required? Is it possible to avoid writing on files?

**Comment by PabloPiaggi** [comment]
With Gareth's new implementation this issue has been solved.
