### ISSUE TITLE
Avoid that the code crashes

### ISSUE THREAD

**Issue by giovannipizzi** [PabloPiaggi/plumed2#9]
- Now, plumed calls an error function and crashes, e.g. if the name passed to `plumed.grab` is not correct. E.g.: `plumed.grab("q7")` returns:

```
********** STACK DUMP **********
[...]
******** END STACK DUMP ********
+++ Internal PLUMED error
+++ file PlumedMain.cpp, line 537
+++ message: cannot find action named q7 (hint! the actions in this ActionSet are: q6 @1 @2 )
Aborted (core dumped)
```

  Can we have a way such that the error is nicely passed back to python, and python just raises an exception? I think this is quite important.
Similarly for asking `q6.x`:

```
+++ Internal PLUMED error
+++ file PlumedMain.cpp, line 527
+++ message: action q6 has no component named x (hint! the components in this actions are: q6.mean q6.min )
Aborted (core dumped)
```
- Also (maybe this is already possible): how to get programmatically the list of components of a given action? (or the order of components when I ask `q6.*`)?

**Comment by PabloPiaggi** [comment]
Ok. I can change the type of error such that plumed exits silently. Then we can pass the error nicely to python.

**Comment by giovannipizzi** [comment]
Ok. Just I'm not sure you should call any 'exit' call, otherwise probably also python exits (but try it). Probably the way to do it is to return normally with some special value set (e.g. adding and additional parameter like status, that if is different from zero means an error), and then converting this to an exception in Python.
